# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66a5b1aca4a1d705b04f967f975bb30f904dbe4e28411603e975a19c8a0ae002b3a105d2f61651d192760bafdf4fc92e543628b81b96d09d79ff7504c3caf18

test:
  secret_key_base: 79ea57b37d97f77db7b72e3064ce9407c165c8db3d8eaa714300bb4ac529f32a2f3c8f89d28950ae8bee6cdc349c80fadc42d50bde89750885b70051bdcc3ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
