# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "answer_records", :force => true do |t|
    t.column "problem",          :string
    t.column "decoded_answer",   :string
    t.column "start_time",       :datetime
    t.column "test_result_id",   :integer
    t.column "course_id",        :integer
    t.column "test_template_id", :integer
  end

  create_table "courses", :force => true do |t|
    t.column "course_name",   :string
    t.column "class_number",  :string
    t.column "instructor_id", :integer
  end

  create_table "courses_students", :id => false, :force => true do |t|
    t.column "course_id",  :integer
    t.column "student_id", :integer
  end

  add_index "courses_students", ["course_id", "student_id"], :name => "index_courses_students_on_course_id_and_student_id"
  add_index "courses_students", ["student_id"], :name => "index_courses_students_on_student_id"

  create_table "courses_test_templates", :id => false, :force => true do |t|
    t.column "course_id",        :integer
    t.column "test_template_id", :integer
  end

  add_index "courses_test_templates", ["course_id", "test_template_id"], :name => "index_courses_test_templates_on_course_id_and_test_template_id"
  add_index "courses_test_templates", ["test_template_id"], :name => "index_courses_test_templates_on_test_template_id"

  create_table "instructors", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "students", :force => true do |t|
    t.column "first_name",     :string
    t.column "last_name",      :string
    t.column "student_number", :string
  end

  create_table "test_results", :force => true do |t|
    t.column "answers",          :string
    t.column "test_items",       :text
    t.column "score",            :float
    t.column "status",           :string
    t.column "start_time",       :datetime
    t.column "student_id",       :integer
    t.column "course_id",        :integer
    t.column "test_template_id", :integer
  end

  create_table "test_templates", :force => true do |t|
    t.column "name",          :string
    t.column "template",      :text
    t.column "description",   :string
    t.column "course_id",     :integer
    t.column "instructor_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "user_name",  :string
    t.column "password",   :string
    t.column "role",       :string
  end

end
