require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnswerRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # AnswerRecord. As you add validations to AnswerRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnswerRecordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all answer_records as @answer_records" do
      answer_record = AnswerRecord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:answer_records).should eq([answer_record])
    end
  end

  describe "GET show" do
    it "assigns the requested answer_record as @answer_record" do
      answer_record = AnswerRecord.create! valid_attributes
      get :show, {:id => answer_record.to_param}, valid_session
      assigns(:answer_record).should eq(answer_record)
    end
  end

  describe "GET new" do
    it "assigns a new answer_record as @answer_record" do
      get :new, {}, valid_session
      assigns(:answer_record).should be_a_new(AnswerRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested answer_record as @answer_record" do
      answer_record = AnswerRecord.create! valid_attributes
      get :edit, {:id => answer_record.to_param}, valid_session
      assigns(:answer_record).should eq(answer_record)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnswerRecord" do
        expect {
          post :create, {:answer_record => valid_attributes}, valid_session
        }.to change(AnswerRecord, :count).by(1)
      end

      it "assigns a newly created answer_record as @answer_record" do
        post :create, {:answer_record => valid_attributes}, valid_session
        assigns(:answer_record).should be_a(AnswerRecord)
        assigns(:answer_record).should be_persisted
      end

      it "redirects to the created answer_record" do
        post :create, {:answer_record => valid_attributes}, valid_session
        response.should redirect_to(AnswerRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved answer_record as @answer_record" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerRecord.any_instance.stub(:save).and_return(false)
        post :create, {:answer_record => {  }}, valid_session
        assigns(:answer_record).should be_a_new(AnswerRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerRecord.any_instance.stub(:save).and_return(false)
        post :create, {:answer_record => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested answer_record" do
        answer_record = AnswerRecord.create! valid_attributes
        # Assuming there are no other answer_records in the database, this
        # specifies that the AnswerRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnswerRecord.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => answer_record.to_param, :answer_record => { "these" => "params" }}, valid_session
      end

      it "assigns the requested answer_record as @answer_record" do
        answer_record = AnswerRecord.create! valid_attributes
        put :update, {:id => answer_record.to_param, :answer_record => valid_attributes}, valid_session
        assigns(:answer_record).should eq(answer_record)
      end

      it "redirects to the answer_record" do
        answer_record = AnswerRecord.create! valid_attributes
        put :update, {:id => answer_record.to_param, :answer_record => valid_attributes}, valid_session
        response.should redirect_to(answer_record)
      end
    end

    describe "with invalid params" do
      it "assigns the answer_record as @answer_record" do
        answer_record = AnswerRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => answer_record.to_param, :answer_record => {  }}, valid_session
        assigns(:answer_record).should eq(answer_record)
      end

      it "re-renders the 'edit' template" do
        answer_record = AnswerRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => answer_record.to_param, :answer_record => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested answer_record" do
      answer_record = AnswerRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => answer_record.to_param}, valid_session
      }.to change(AnswerRecord, :count).by(-1)
    end

    it "redirects to the answer_records list" do
      answer_record = AnswerRecord.create! valid_attributes
      delete :destroy, {:id => answer_record.to_param}, valid_session
      response.should redirect_to(answer_records_url)
    end
  end

end
